#!/bin/sh
# -*- coding: utf-8 -*-

set -e

if mountpoint -q /pst; then
    cgroupfs.mount && dockerd -s overlay -g /pst/lib/docker < /dev/null &> /dev/null &
else
    cgroupfs.mount && dockerd -s vfs < /dev/null &> /dev/null &
fi
