#!/bin/sh

### BEGIN INIT INFO
# Provides:            boot
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 6
# Short-Description:   Runs the complete set of Scudum boot scripts.
# Description:         Runs the complete set of Scudum boot scripts.
### END INIT INFO

. /lib/lsb/init-functions

do_start() {
    log_info_msg "Touching scudum running file (/etc/scudum/RUNNING)"
    echo $(date +%Y%m%d%H%M%S) > /etc/scudum/RUNNING
    log_success_msg2
    log_info_msg "Running scudum boot scripts (/etc/boot/*)"
    for file in /etc/boot/*; do
        $file
    done
    log_success_msg2
}

do_stop() {
    log_info_msg "Running scudum halt scripts (/etc/boot/*)"
    for file in /etc/halt/*; do
        $file
    done
    log_success_msg2
}

case "$1" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;
esac

exit 0
