#! /bin/sh

### BEGIN INIT INFO
# Provides:            boot
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:
# Short-Description:   Runs the complete set of Scudum boot scripts.
# Description:         Runs the complete set of Scudum boot scripts.
### END INIT INFO

. /lib/lsb/init-functions

do_start() {
    log_info_msg "Running scudum boot scripts (/etc/boot/*)"
    for file in /etc/boot/*; do
        $file
    done
    echo_ok
}

case "$1" in
    start)
        do_start
        ;;

    stop)
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;
esac

exit 0
