#!/bin/sh

### BEGIN INIT INFO
# Provides:            checkcd
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Runs a series of validations for tmpfs systems.
# Description:         Runs a series of validations for tmpfs systems.
### END INIT INFO

. /lib/lsb/init-functions

# ammount of time that is going to be spent in the boot
# process to wait for the devices to become available,
# note that usb devices are asynchronous in loading
SLEEP=3

# the name of the volume label that is going to be used
# for finding the persistent storage devices
STORAGE=PSTSCU

case "${1}" in
    start)
        log_info_msg "Waiting for /dev to become populated..."
        sleep $SLEEP
        evaluate_retval

        log_info_msg "Making /tmp world writeable (1777)..."
        chmod 1777 /tmp
        evaluate_retval

        # verifies if the current system structure contains the
        # persistence structure and if that's not the case, exits
        # the current working login, nothing remaining to be done
        if [ ! -d /initrd ]; then exit; fi

        log_info_msg "Releasing unused memory from initrd..."
        umount /initrd/proc
        umount -l /initrd
        rm -rf /initrd
        evaluate_retval

        log_info_msg "Mounting persistent storage..."
        storage=$(lsblk --pairs -o NAME,LABEL | grep "LABEL=\"$STORAGE\"" |\
            cut -d \  -f 1 | cut -b 7- | cut -d \" -f 1)
        for device in $storage; do
            mkdir -p pst && mount /dev/$device pst
            break
        done
        evaluate_retval
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0
