#!/bin/sh

### BEGIN INIT INFO
# Provides:            checkcd
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Runs a series of validations for tmpfs systems.
# Description:         Runs a series of validations for tmpfs systems.
### END INIT INFO

. /lib/lsb/init-functions

if [ ! -d /origin ]; then exit; fi

log_info_msg "Making /tmp world writeable (1777)..."
chmod 1777 /tmp
evaluate_retval

log_info_msg "Releasing unused memory from initrd..."
umount /initrd/proc
umount -l /initrd
rm -rf /initrd
evaluate_retval

exit 0
