#!/bin/sh

### BEGIN INIT INFO
# Provides:            cleanfs
# Required-Start:      $local_fs
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Cleans temporary directories early in the boot process.
# Description:         Cleans temporary directories /var/run, /var/lock, and
#                      optionally, /tmp.  cleanfs also creates /var/run/utmp 
#                      and any files defined in /etc/sysconfig/createfiles.
### END INIT INFO

. /lib/lsb/init-functions

create_files() {
    # inputs to file descriptor 9 and output to stdin (redirection)
    exec 9>&0 < /etc/sysconfig/createfiles

    while read name type perm usr grp dtype maj min junk; do
        # ignores comments and blank lines
        case "${name}" in
            ""|\#*) continue ;;
        esac

        # ignores existing files
        if [ ! -e "${name}" ]; then
            # creates stuff based on its type
            case "${type}" in
                dir)
                    mkdir "${name}"
                    ;;
                file)
                    :> "${name}"
                    ;;
                dev)
                    case "${dtype}" in
                        char)
                            mknod "${name}" c ${maj} ${min}
                            ;;
                        block)
                            mknod "${name}" b ${maj} ${min}
                            ;;
                        pipe)
                            mknod "${name}" p
                            ;;
                        *)
                            log_warning_msg "\nUnknown device type: ${dtype}" 
                            ;;
                    esac
                    ;;
                *)
                    log_warning_msg "\nUnknown type: ${type}" 
                    continue
                    ;;
            esac

            # sets up the permissions
            chown ${usr}:${grp} "${name}"
            chmod ${perm} "${name}"
        fi
    done

    # closes file descriptor 9 (end redirection)
    exec 0>&9 9>&-
    return 0
}

case "${1}" in
    start)
        log_info_msg "Cleaning file systems:" 

        if [ "${SKIPTMPCLEAN}" = "" ]; then
            log_info_msg2 " /tmp" 
            cd /tmp &&
            find . -xdev -mindepth 1 ! -name lost+found -delete || failed=1
        fi

        > /var/run/utmp

        if grep -q '^utmp:' /etc/group ; then
            chmod 664 /var/run/utmp
            chgrp utmp /var/run/utmp
        fi

        (exit ${failed})
        evaluate_retval

        if egrep -qv '^(#|$)' /etc/sysconfig/createfiles 2>/dev/null; then
            log_info_msg "Creating files and directories... "
            create_files
            evaluate_retval
        fi

        exit $failed
        ;;
    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0
