#!/bin/sh

### BEGIN INIT INFO
# Provides:            console
# Required-Start:
# Should-Start:        $local_fs
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Sets up a localised console.
# Description:         Sets up fonts and language settings for the user's
#                      local as defined by /etc/sysconfig/console.
### END INIT INFO

. /lib/lsb/init-functions

# verifies if the console configuration file exists and
# in case it does loads the configuration from it
[ -r /etc/sysconfig/console ] && . /etc/sysconfig/console

function is_true() {
    [ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ]
}

failed=0

case "${1}" in
    start)
        # checks if we need to do anything by veryfing each of the
        # target variables for prcesence, in case none of them is
        # defined the current flow is returned (nothing to be done)
        if [ -z "${KEYMAP}" ] && [ -z "${KEYMAP_CORRECTIONS}" ] &&
            [ -z "${FONT}" ] && [ -z "${LEGACY_CHARSET}" ] &&     
            ! is_true "${UNICODE}"; then 
            exit 0
        fi

        # prints an information about the console configuration
        # process that is about to begin
        log_info_msg "Setting up Linux console..."

        # figures out if a framebuffer console is used
        [ -d /sys/class/graphics/fb0 ] && use_fb=1 || use_fb=0

        # figures out the command to set the console into the
        # desired mode
        is_true "${UNICODE}" &&
            MODE_COMMAND="echo -en '\033%G' && kbd_mode -u" ||
            MODE_COMMAND="echo -en '\033%@\033(K' && kbd_mode -a"

        # on framebuffer consoles, font has to be set for each vt in
        # UTF-8 mode, this doesn't hurt in non-UTF-8 mode also
        ! is_true "${use_fb}" || [ -z "${FONT}" ] ||
            MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"

        # aplies that command to all consoles mentioned in
        # /etc/inittab as expected by the configuration
        for TTY in `grep '^[^#].*respawn:/sbin/agetty' /etc/inittab |
            grep -o '\btty[[:digit:]]*\b'`; do
            openvt -f -w -c ${TTY#tty} -- \
                /bin/sh -c "${MODE_COMMAND}" || failed=1
        done

        # sets the font (if not already set above) and the keymap
        [ "${use_fb}" == "1" ] || [ -z "${FONT}" ] || setfont $FONT || failed=1

        [ -z "${KEYMAP}" ] ||
            loadkeys ${KEYMAP} >/dev/null 2>&1 ||
            failed=1

        [ -z "${KEYMAP_CORRECTIONS}" ] ||
            loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 ||
            failed=1

        # converts the keymap from $LEGACY_CHARSET to UTF-8
        [ -z "$LEGACY_CHARSET" ] ||
            dumpkeys -c "$LEGACY_CHARSET" | loadkeys -u >/dev/null 2>&1 ||
            failed=1

        # if any of the commands above failed, the trap at the
        # top would set $failed to 1
        ( exit $failed ) 
        evaluate_retval

        exit $failed
        ;;

    *)
        echo "Usage:  ${0} {start}"
        exit 1
        ;;
esac

exit 0
