#!/bin/sh

### BEGIN INIT INFO
# Provides:            modules
# Required-Start:      mountvirtfs sysctl
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Loads required modules.
# Description:         Loads modules listed in /etc/sysconfig/modules.
### END INIT INFO

[ -e /proc/ksyms -o -e /proc/modules ] || exit 0

. /lib/lsb/init-functions

case "${1}" in
    start)
        [ -r /etc/sysconfig/modules ] || exit 0
        egrep -qv '^($|#)' /etc/sysconfig/modules || exit 0

        log_info_msg "Loading modules:" 

        while read module args; do

            case "$module" in
                ""|"#"*) continue ;;
            esac

            modprobe ${module} ${args} > /dev/null

            if [ $? -eq 0 ]; then
                log_info_msg2 " ${module}" 
            else
                failedmod="${failedmod} ${module}"
            fi

        done < /etc/sysconfig/modules

        log_success_msg2

        if [ -n "${failedmod}" ]; then
            log_failure_msg "Failed to load modules:${failedmod}" 
            exit 1
        fi
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0
