#!/bin/sh

### BEGIN INIT INFO
# Provides:            mountvirtfs
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Mounts /sys and /proc virtual (kernel) filesystems.
#                      Mounts /run (tmpfs) and /dev (devtmpfs).
# Description:         Mounts /sys and /proc virtual (kernel) filesystems.
#                      Mounts /run (tmpfs) and /dev (devtmpfs).
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        # makes sure /run/var is available before logging any messages
        if ! mountpoint /run >/dev/null; then
            mount -n /run || failed=1
        fi

        mkdir -p /run/var /run/lock /run/shm
        chmod 1777 /run/shm

        log_info_msg "Mounting virtual file systems: ${INFO}/run" 

        if ! mountpoint /proc >/dev/null; then
            log_info_msg2 " ${INFO}/proc"
            mount -n -o nosuid,noexec,nodev /proc || failed=1
        fi

        if ! mountpoint /sys >/dev/null; then
            log_info_msg2 " ${INFO}/sys" 
            mount -n -o nosuid,noexec,nodev /sys || failed=1
        fi

        if ! mountpoint /dev >/dev/null; then
            log_info_msg2 " ${INFO}/dev" 
            mount -n -o mode=0755,nosuid /dev  || failed=1
        fi

        # copies devices that Udev >= 155 doesn't handle to /dev
        cp -a /lib/udev/devices/* /dev

        ln -sfn /run/shm /dev/shm
      
        (exit ${failed})
        evaluate_retval
        exit $failed
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
