#!/bin/sh

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
### END INIT INFO

case "${1}" in
    start)
        # iterates over the complete set of interface configuration
        # files to start their respective configuration
        for file in /etc/sysconfig/ifconfig.*; do
            interface=${file##*/ifconfig.}

            # in case the current interface is the wildcard character
            # no expansion was performed (skips iteration)
            if [ "${interface}" = "*" ]; then
                continue
            fi

            /sbin/ifup ${interface}
        done
        ;;

    stop)
        # reverses the list so that the iteration for the stop
        # operation is performed in reverse order
        net_files=""
        for file in  /etc/sysconfig/ifconfig.*; do
            net_files="${file} ${net_files}"
        done

        for file in ${net_files}; do
            interface=${file##*/ifconfig.}

            if [ "${interface}" = "*" ]; then
                continue
            fi

            /sbin/ifdown ${interface}
        done
        ;;

    restart)
        ${0} stop
        sleep 1
        ${0} start
        ;;

    *)
        echo "Usage: ${0} {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
