#!/bin/sh

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
### END INIT INFO

case "${1}" in
    start)
        # starts all network interfaces
        for file in /etc/sysconfig/ifconfig.*
        do
            interface=${file##*/ifconfig.}

            # skips if $file is * (because nothing was found)
            if [ "${interface}" = "*" ]; then
                continue
            fi

            /sbin/ifup ${interface}
        done
        ;;

    stop)
        # reverses the list
        net_files=""
        for file in  /etc/sysconfig/ifconfig.*; do
            net_files="${file} ${net_files}"
        done

        # stops all network interfaces
        for file in ${net_files}; do
            interface=${file##*/ifconfig.}

            # skips if $file is * (because nothing was found)
            if [ "${interface}" = "*" ]; then
                continue
            fi

            /sbin/ifdown ${interface}
        done
        ;;

    restart)
        ${0} stop
        sleep 1
        ${0} start
        ;;

    *)
        echo "Usage: ${0} {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
