#!/bin/sh

### BEGIN INIT INFO
# Provides:            
# Required-Start:
# Should-Start:        modules
# Required-Stop:
# Should-Stop:         $syslog
# Default-Start:       S
# Default-Stop:
# Short-Description:   Stores and restores time from the hardware clock
# Description:         On boot, system time is obtained from hwclock.  The
#                      hardware clock can also be set on shutdown.
### END INIT INFO

. /lib/lsb/init-functions

[ -r /etc/sysconfig/clock ] && . /etc/sysconfig/clock

NTP=0

for argument in $(cat /proc/cmdline); do
    case "${argument}" in
        ntp)
            NTP=1
            ;;
    esac
done

case "${UTC}" in
    yes|true|1)
        CLOCKPARAMS="${CLOCKPARAMS} --utc"
        ;;

    no|false|0)
        CLOCKPARAMS="${CLOCKPARAMS} --localtime"
        ;;
esac

case ${1} in
    start)
        if [ "$NTP" == "1" ] && [ -e /usr/bin/ntpdate ]; then
            log_info_msg "Setting hardware clock, using NTP (pool.ntp.org)..."
            ntpdate pool.ntp.org > /dev/null
            evaluate_retval
        else
            hwclock --hctosys ${CLOCKPARAMS} > /dev/null
        fi
        ;;

    stop)
        if [ "$NTP" == "0" ]; then
            log_info_msg "Setting hardware clock..."
            hwclock --systohc ${CLOCKPARAMS} > /dev/null
            evaluate_retval
        fi
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;

esac

exit 0
