#!/bin/sh

### BEGIN INIT INFO
# Provides:            
# Required-Start:
# Should-Start:        modules
# Required-Stop:
# Should-Stop:         $syslog
# Default-Start:       S
# Default-Stop:
# Short-Description:   Stores and restores time from the hardware clock
# Description:         On boot, system time is obtained from hwclock.  The
#                      hardware clock can also be set on shutdown.
### END INIT INFO

. /lib/lsb/init-functions

[ -r /etc/sysconfig/clock ] && . /etc/sysconfig/clock

NTP=0
NTP_FIRST_SERVER=pool.ntp.org
NTP_SECOND_SERVER=time.google.com
NTP_RETRIES=10
NTP_SLEEP=5

for argument in $(cat /proc/cmdline); do
    case "${argument}" in
        ntp)
            NTP=1
            ;;
    esac
done

case "${UTC}" in
    yes|true|1)
        CLOCKPARAMS="${CLOCKPARAMS} --utc"
        ;;

    no|false|0)
        CLOCKPARAMS="${CLOCKPARAMS} --localtime"
        ;;
esac

case ${1} in
    start)
        if [ "$NTP" == "1" ]; then
            if [ -e /usr/bin/ntpdate ]; then
                log_info_msg "Setting hardware clock, using NTP (${NTP_FIRST_SERVER}, ${NTP_SECOND_SERVER})..."
                n=0
                executed=0
                while [ true ]; do
                    if [ $n -eq $NTP_RETRIES ]; then
                        break
                    fi
                    ntpdate -s ${NTP_FIRST_SERVER}
                    if [ $? -eq 0 ]; then
                        executed=1
                        break
                    fi
                    ntpdate -s ${NTP_SECOND_SERVER}
                    if [ $? -eq 0 ]; then
                        executed=1
                        break
                    fi
                    sleep ${NTP_SLEEP}
                    let n+=1
                done
                if [ $executed -eq 0 ]; then
                    false
                fi
                evaluate_retval
            fi
        else
            hwclock --hctosys ${CLOCKPARAMS} > /dev/null
        fi
        ;;

    stop)
        if [ "$NTP" == "0" ]; then
            log_info_msg "Setting hardware clock..."
            hwclock --systohc ${CLOCKPARAMS} > /dev/null
            evaluate_retval
        fi
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;

esac

exit 0
