#!/bin/sh

### BEGIN INIT INFO
# Provides:            splash
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Runs the initial splash screen.
# Description:         Runs the initial splash screen.
### END INIT INFO

. /lib/lsb/init-functions

SPLASH=0

for ARGUMENT in $(cat /proc/cmdline); do
    case "${ARGUMENT}" in
        splash*)
            SPLASH=1
            ;;

        nosplash*)
            SPLASH=0
            ;;
    esac
done

case "${1}" in
    start)
        if [ "$SPLASH" == "0" ]; then exit; fi
        if [ ! -e /sbin/plymouthd ]; then exit; fi
        if [ ! -e /bin/plymouth ]; then exit; fi

        /sbin/plymouthd --mode=boot
        /bin/plymouth show-splash
        ;;

    stop)
        if [ "$SPLASH" == "0" ]; then exit; fi
        if [ ! -e /sbin/plymouthd ]; then exit; fi
        if [ ! -e /bin/plymouth ]; then exit; fi

        /bin/plymouth quit
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0
