#!/bin/sh

### BEGIN INIT INFO
# Provides:            spashe
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       1 2 3 4 5
# Default-Stop:
# Short-Description:   Runs the end operation of splash screen.
# Description:         Runs the end operation of splash screen.
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        if [ ! -e /sbin/plymouthd ]; then exit; fi
        if [ ! -e /bin/plymouth ]; then exit; fi

        log_info_msg "Stopping plymouth splash screen..."
        /bin/plymouth quit
        evaluate_retval
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        exit 1
        ;;
esac

exit 0
