#!/bin/sh

### BEGIN INIT INFO
# Provides:            splash
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Runs the initial splash screen.
# Description:         Runs the initial splash screen.
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        if [ ! -e /sbin/plymouthd ]; then exit; fi
        if [ ! -e /bin/plymouth ]; then exit; fi

        /sbin/plymouthd --mode=boot
        /bin/plymouth show-splash
        evaluate_retval
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0
