#!/bin/sh

### BEGIN INIT INFO
# Provides:            sshd
# Required-Start:      $network
# Should-Start:
# Required-Stop:       sendsignals
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 6
# Short-Description:   Starts sshd daemon.
# Description:         Starts sshd daemon.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        log_info_msg "Starting SSH Server..."
        test -f /etc/ssh/ssh_host_dsa_key || /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N "" -C "" < /dev/null &> /dev/null
        test -f /etc/ssh/ssh_host_rsa_key || /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N "" -C "" < /dev/null &> /dev/null
        test -f /etc/ssh/ssh_host_dsa_key || /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N "" -C "" < /dev/null &> /dev/null
        test -f /etc/ssh/ssh_host_ecdsa_key || /usr/bin/ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N "" -C "" < /dev/null &> /dev/null
        test -f /etc/ssh/ssh_host_ed25519_key || /usr/bin/ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -C "" < /dev/null &> /dev/null
        start_daemon -f /usr/sbin/sshd
        evaluate_retval
        sleep 1
        pid=$(cat /var/run/sshd.pid 2>/dev/null)
        echo "-16" >/proc/${pid}/oom_score_adj
        ;;

    stop)
        log_info_msg "Stopping SSH Server..."
        killproc -p "/var/run/sshd.pid" /usr/sbin/sshd
        evaluate_retval
        ;;

    reload)
        log_info_msg "Reloading SSH Server..."
        pid=$(cat /var/run/sshd.pid 2>/dev/null)

        if [ -n "${pid}" ]; then
           kill -HUP "${pid}"
        else
           (exit 1)
        fi

        evaluate_retval
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        statusproc /usr/sbin/sshd
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
        ;;
esac

exit 0
