#!/bin/sh

### BEGIN INIT INFO
# Provides:            welcome
# Required-Start:
# Should-Start:
# Required-Stop: 
# Should-Stop:
# Default-Start:       1 2 3 4 5
# Default-Stop:
# Short-Description:   Shows welcome/diagnostics information.
# Description:         Shows welcome/diagnostics information.
### END INIT INFO

. /etc/colors

DISTRIB=$(cat /etc/scudum/DISTRIB)
VERSION=$(cat /etc/scudum/VERSION)
KVERSION=$(uname -r)
SVERSION=$DISTRIB-$VERSION
ADDRESS=$(ifconfig | sed -n "s/.*inet addr:\([0-9.]\+\)\s.*/\1/p" | grep -v "127.0.0.1")
PROCESS_COUNT=$(ps --ppid 2 -p 2 --deselect -o user | wc -l) 

case "${1}" in
    start)
        echo -e "Linux "$COLOR_GREEN"Scudum"$COLOR_RESET" $SVERSION (GNU/Linux $KVERSION)"
        echo -e "Copyright Hive Solutions Lda. 2008-2014"
        echo -e ""
        echo -e "  IP address: $ADDRESS"
        echo -e "  Processes: $PROCESS_COUNT"
        for file in /etc/welcome/*; do
            . $file
        done
        exit 0
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

exit 0