#!/bin/sh
# -*- coding: utf-8 -*-

export ARMOR_BASE_URL=${ARMOR_BASE_URL-http://armor:8080/api/}
export ARMOR_USERNAME=${ARMOR_USERNAME-root}
export ARMOR_PASSWORD=${ARMOR_PASSWORD-root}

set -e

source /etc/environ

armorc halt
