#!/bin/sh
# -*- coding: utf-8 -*-

export DATA_ORIGIN=${DATA_ORIGIN-//files.hive/data}
export DATA_TARGET=${DATA_TARGET-/mnt/data}
export DATA_USERNAME=${DATA_USERNAME-bot_admin}
export DATA_PASSWORD=${DATA_PASSWORD-anonymous}
export ARMOR_SERVER=${ARMOR_SERVER-netius}
export ARMOR_HOST=${ARMOR_HOST-0.0.0.0}
export ARMOR_PORT=${ARMOR_PORT-8080}
export ARMOR_SESSION=${ARMOR_SESSION-memory}
export ARMOR_ADAPTER=${ARMOR_ADAPTER-tiny}
export ARMOR_TINY_PATH=${ARMOR_TINY_PATH-$DATA_TARGET/tiny/armor.json}

set -e

source /etc/environ

mkdir -p $DATA_TARGET && mount -t cifs -o username=$DATA_USERNAME,password=$DATA_PASSWORD $DATA_ORIGIN $DATA_TARGET

pip install --quiet netius tinydb armord

SERVER=$ARMOR_SERVER \
HOST=$ARMOR_HOST \
PORT=$ARMOR_PORT \
SESSION=$ARMOR_SESSION \
ADAPTER=$ARMOR_ADAPTER \
TINY_PATH=$ARMOR_TINY_PATH \
armord < /dev/null &> /var/log/armord.out.log &
