#!/bin/bash

copy() {
    local file

    if [ "$2" == "lib" ]; then
        file=$(PATH=/lib:/usr/lib type -p $1)
    else
        file=$(PATH=/sbin:/usr/sbin:/bin:/usr/bin type -p $1)
    fi
    
    echo "$file"

    if [ -n $file ] ; then
        cp $file $TEMP_DIR/$2
    else
        echo "Missing required file: $1 for directory $2"
        rm -rf $TEMP_DIR
        exit 1
    fi
}

# intializes any of the control flags that will handle
# and control the way the package is going to be created
USE_FIRMWARE=${USE_FIRMWARE-1}

if [ -z $1 ] ; then
    INITRAMFS_FILE=initrd.img
else
    KERNEL_VERSION=$1
    INITRAMFS_FILE=initrd.img
fi

if [ -n "$KERNEL_VERSION" ] && [ ! -d "/lib/modules/$1" ] ; then
    echo "No modules directory named $1"
    exit 1
fi

printf "Creating $INITRAMFS_FILE... "

binfiles="bash cat cp dd killall ls mkdir mknod mount "
binfiles="$binfiles umount sed sleep ln rm uname grep "
binfiles="$binfiles egrep cut tar gzip touch"

# systemd installs udevadm in /bin. Other udev implementations
# have it in /sbin, take note of possible problems/issues
if [ -x /bin/udevadm ] ; then binfiles="$binfiles udevadm"; fi

# creates the initial set of files from the system binaries set
# that are going to be copied into the initrd file
sbinfiles="modprobe blkid switch_root pivot_root"

# optional files and locations, meaning that if they don't exist
# there's no critical error to be raised (optional)
for file in mdadm udevd udevadm; do
    if [ -x /sbin/$file ] ; then sbinfiles="$sbinfiles $file"; fi
done

# initializes a new temporary file that will be used to store
# the complete set of libraries that are considered dependencies
unsorted=$(mktemp /tmp/unsorted.XXXXXXXXXX)

# creates the function that is responsible for the retrieval of
# file dependencies and storage under the unsorted file for operation
# the operation should be cross compilation ready
unsort() {
    if [ -e /cross/bin/cross-ldd ]; then
        (cross-ldd $(type -p $1) | sed "s/\t//" | cut -d " " -f1 >> $unsorted) &> /dev/null
    else
        ldd $(type -p $1) | sed "s/\t//" | cut -d " " -f1 >> $unsorted
    fi
}

# initializes the global variables that refer the operations
# that are going to be parts of the initird creation
DATADIR=/usr/share/mkinitramfs
INIT_IN=linuxrc

# creates a temporrary working directory, where the
# files will be stored for the creation of the image
TEMP_DIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)

# creates the ramdisk file and zeros it taking into
# account the requested size (this is very important)
rm -f ramdisk
dd if=/dev/zero of=ramdisk bs=1k count=131072 &> /dev/null
losetup /dev/loop1 ramdisk

# creates the the ext2 based file system in the loop
# device and then mounts it under the temporary directory
mke2fs /dev/loop1 &> /dev/null
mkdir -p /mnt/loop1
mount /dev/loop1 $TEMP_DIR
rm -rf $TEMP_DIR/lost+found

# creates base directory structure
mkdir -p $TEMP_DIR/{bin,dev,lib/firmware,run,sbin,sys,proc}
mkdir -p $TEMP_DIR/etc/{modprobe.d,udev/rules.d}
touch $TEMP_DIR/etc/modprobe.d/modprobe.conf
ln -s lib $TEMP_DIR/lib64

# creates necessary device nodes, that are going to be used
# for some of the operation in the construction of intrd
mknod -m 640 $TEMP_DIR/dev/console c 5 1
mknod -m 664 $TEMP_DIR/dev/null c 1 3

# installs the udev configuration files
if [ -f /etc/udev/udev.conf ]; then
    cp /etc/udev/udev.conf $TEMP_DIR/etc/udev/udev.conf
fi

for file in $(find /etc/udev/rules.d/ -type f) ; do
    cp $file $TEMP_DIR/etc/udev/rules.d
done

# installs any firmware present, if the flag
# that controls it's copy is set and defined,
# note that this may be a large copy
if [ "$USE_FIRMWARE" == "1" ]; then
    cp -a /lib/firmware $TEMP_DIR/lib
fi

# copies the RAID configuration file if present
if [ -f /etc/mdadm.conf ] ; then
    cp /etc/mdadm.conf $TEMP_DIR/etc
fi

# installs the init file that will be used for the initial
# loading stage of the linux kernel
install -m0755 $DATADIR/$INIT_IN $TEMP_DIR/linuxrc

if [ -n "$KERNEL_VERSION" ] ; then
    if [ -x /bin/kmod ] ; then
        binfiles="$binfiles kmod"
    else
        binfiles="$binfiles lsmod"
        sbinfiles="$sbinfiles insmod"
    fi
fi

# installs basic binaries, that may be used under the
# the linux rc script for processing
for file in $binfiles ; do
    unsort $file
    copy $file bin
done

# adds lvm if present to the set of files that are considered
# to be the system binaries (sbin)
if [ -x /sbin/lvm ] ; then sbinfiles="$sbinfiles lvm dmsetup"; fi

for file in $sbinfiles ; do
    unsort $file
    copy $file sbin
done

# adds udevd libraries if not in /sbin, so that they may be used
# to load extra drivers durring the initial boot sequence
if [ -x /lib/udev/udevd ] ; then
    unsort /lib/udev/udevd
elif [ -x /lib/systemd/systemd-udevd ] ; then
    unsort /lib/systemd/systemd-udevd
fi

# creates some of the binaries symbolic links so that legacy
# support is enabled for all the operations
ln -s bash $TEMP_DIR/bin/sh

# adds module symlinks if appropriate
if [ -n "$KERNEL_VERSION" ] && [ -x /bin/kmod ] ; then
    ln -s kmod $TEMP_DIR/bin/lsmod
    ln -s kmod $TEMP_DIR/bin/insmod
fi

# adds lvm symlinks if appropriate, also copies
# the lvm.conf file
if  [ -x /sbin/lvm ] ; then
    ln -s lvm $TEMP_DIR/sbin/lvchange
    ln -s lvm $TEMP_DIR/sbin/lvrename
    ln -s lvm $TEMP_DIR/sbin/lvextend
    ln -s lvm $TEMP_DIR/sbin/lvcreate
    ln -s lvm $TEMP_DIR/sbin/lvdisplay
    ln -s lvm $TEMP_DIR/sbin/lvscan

    ln -s lvm $TEMP_DIR/sbin/pvchange
    ln -s lvm $TEMP_DIR/sbin/pvck
    ln -s lvm $TEMP_DIR/sbin/pvcreate
    ln -s lvm $TEMP_DIR/sbin/pvdisplay
    ln -s lvm $TEMP_DIR/sbin/pvscan

    ln -s lvm $TEMP_DIR/sbin/vgchange
    ln -s lvm $TEMP_DIR/sbin/vgcreate
    ln -s lvm $TEMP_DIR/sbin/vgscan
    ln -s lvm $TEMP_DIR/sbin/vgrename
    ln -s lvm $TEMP_DIR/sbin/vgck

    cp -a /etc/lvm $TEMP_DIR/etc
fi

# installs libraries into the proper directory
# so that they may be used at runtime, note that
# the unsorted (including duplicates) list is sorted
# so that duplicated values/libraries are removed
sort $unsorted | uniq | while read library ; do
    if [[ "$library" != *".so"* ]] ||
        [ "$library" == "linux-vdso.so.1" ] ||
        [ "$library" == "linux-gate.so.1" ]; then
        continue
    fi

    copy $library lib
done

if [ -d /lib/udev ]; then
    cp -a /lib/udev $TEMP_DIR/lib
fi
if [ -d /lib/systemd ]; then
    cp -a /lib/systemd $TEMP_DIR/lib
fi

# installs the kernel modules if they were requested
# these may be used at initram time so that extra dev
# functionality is enabled and may be used
if [ -n "$KERNEL_VERSION" ]; then
    cp /lib/modules/$KERNEL_VERSION/modules.{builtin,order}\
        $TEMP_DIR/lib/modules/$KERNEL_VERSION

    depmod -b $TEMP_DIR $KERNEL_VERSION
fi

# syncs the current filesystem and the unmounts
# it removing then the directory reference
sync
umount $TEMP_DIR
losetup -d /dev/loop1
rm -rf $TEMP_DIR

# runs the compression of the ramdisk into the init
# rma file and then removes the ramdisk file (as it
# is no longer required for the operation)
gzip -9 -c ramdisk > $INITRAMFS_FILE
rm -rf ramdisk

# copies the initramfs file to the various repositories
# of information that are valid for booting, and then removes
# the original file as it's not longer required
rm -f /boot/$INITRAMFS_FILE && cp $INITRAMFS_FILE /boot/$INITRAMFS_FILE
rm -f $INITRAMFS_FILE

# remove the temporary directory and file (no longer required)
# and prints a message about the end of the operation
rm -rf $TEMP_DIR $unsorted
printf "done.\n"
