#!/bin/sh
# -*- coding: utf-8 -*-

set -e

source /etc/environ

pip install --quiet netius redis

git clone --depth 1 https://github.com/hivesolutions/dns_registers
mkdir-p /etc/bind && mv dns_registers /etc/bind
ln -s /etc/bind/dns_registers/configuration/named.conf /etc/bind/named.conf
echo "include \"/etc/bind/dns_registers/configuration/bemisc.com.conf\";" >> /etc/bind/named.conf
echo "include \"/etc/bind/dns_registers/configuration/hive.conf\";" >> /etc/bind/named.conf
echo "include \"/etc/bind/dns_registers/configuration/root.conf\";" >> /etc/bind/named.conf

named
