#!/bin/bash

# IFCONFIG=<filename> /lib/services/dhclient <IFACE> <up | down>

. /lib/lsb/init-functions
. $IFCONFIG

STRICT=0
PIDFILE=/run/dhclient-$1.pid
LFILE=/var/lib/dhclient/dhclient-$1.leases

getipstats() {
    # prints the last 16 lines of dhclient.leases
    sed -e :a -e '$q;N;17,$D;ba' ${LFILE}
}

unset is_true

is_true() {
    [ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ] ||
    [ "$1" = "y" ] || [ "$1" = "t" ]
}

case "$2" in
    up)
        if [ -e ${PIDFILE} ]; then
            ps $(cat ${PIDFILE}) | grep dhclient > /dev/null
            if [ "$?" = "0" ]; then
                if [ "$STRICT" == "1" ]; then
                    log_warning_msg "\n dhclient appears to be running on $1"
                else
                    log_success_msg2
                fi
                exit 0
            else
                rm ${PIDFILE}
            fi
        fi

        # runs the dhcp request configuring the requested interface
        # with the data returned from the local dhcp server
        /sbin/dhclient -lf ${LFILE} -pf ${PIDFILE} $DHCP_START $1 &> /dev/null

        # verifies if there was an issue running the dhclient on the
        # requested interface and in case there was logs the error
        # and exists with an error code the caller process
        if [ "$?" != "0" ]; then
            log_failure_msg2
            exit 1
        fi

        # loads the host name value from the current ip stats and then
        # uses it to set the hostname value for the current machine
        HOSTNAME=`getipstats | grep "host-name" | \
            sed 's/ option host-name "//' | \
            sed 's/\";//'`
        if [ "$HOSTNAME" != "" ]; then
            hostname $HOSTNAME
            echo "$(hostname)" > /etc/hostname
            echo "127.0.0.1 localhost $(hostname)" > /etc/hosts
        fi

        # prints the assigned settings if requested
        # retrieving info from dhclient.leases file
        if  is_true "$PRINTIP"  -o  is_true "$PRINTALL"; then

            IPADDR=`getipstats | grep "fixed-address" | \
                sed 's/ fixed-address //' | \
                sed 's/\;//'`

            NETMASK=`getipstats | grep "subnet-mask" | \
                sed 's/ option subnet-mask //' | \
                sed 's/\;//'`

            GATEWAY=`getipstats | grep "routers" | \
                sed 's/ option routers //' | \
                sed 's/\;//'`

            DNS=`getipstats | grep "domain-name-servers" | \
                sed 's/ option domain-name-servers //' | \
                sed 's/\;//' | sed 's/,/ and /'`

            if [ "$PRINTALL" = "yes" ]; then
                log_info_msg "           DHCP Assigned Settings for $1:"
                log_info_msg "           IP Address:      $IPADDR"
                log_info_msg "           Subnet Mask:     $NETMASK"
                log_info_msg "           Default Gateway: $GATEWAY"
                log_info_msg "           DNS Server:      $DNS"
            else
                log_info_msg " IP Addresss:""$IPADDR"
            fi
        fi

        log_success_msg2
        ;;

    down)
        if [ ! -e ${PIDFILE} ]; then
            if [ "$STRICT" == "1" ]; then
                log_warning_msg "\n dhclient doesn't appear to be running on $1"
            else
                log_success_msg2
            fi
            exit 0
        fi

        /sbin/dhclient -r -lf ${LFILE} -pf ${PIDFILE} $DHCP_STOP $1 &> /dev/null

        if [ -e ${PIDFILE} ]; then
            ps $(cat ${PIDFILE}) | grep dhclient > /dev/null

            if [ "$?" != "0" ]; then
                rm -f ${PIDFILE}
            fi
        fi

        evaluate_retval
        ;;

    *)
        echo "Usage: $0 [interface] {up|down}"
        exit 1
        ;;
esac
