#!/bin/bash
# -*- coding: utf-8 -*-

DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

set -e +h

if [ -z "$1" ]; then
    echo "Usage: scudum <command> [<args>]"
    exit 1
fi

if [ ! -e $DIR/build/$1.sh ] && [ ! -e $DIR/util/$1.sh ]; then
    echo "$1: unrecognized command"
    exit 1
fi

if [ -e $DIR/build/$1.sh ]; then
    $DIR/build/$1.sh ${@:2}
fi

if [ -e $DIR/util/$1.sh ]; then
    $DIR/util/$1.sh ${@:2}
fi

exit $?
