name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update
      - run: apt-get install -y -q sudo wget git
      - run: ./travis/build.sh
