name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get update
      - run: sudo apt-get install -y -q wget git
      - run: sudo ./travis/build.sh
