name: Main Workflow
on: [push]

permissions:
  contents: read

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    timeout-minutes: 90
    runs-on: [self-hosted, ubuntu, scudum]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Scudum tools
        run: |
          apt-get update
          apt-get install -y -q wget git
          make install

      - name: Install Scudum root
        run: scudum install

      - name: Build ISO
        run: scudum make.iso
